name: TeaLimit
main: net.teamonster.tealimit.Main
version: ${project.version}
api-version: 1.15
authors: [TeaMaster, Artuto]
description: Limit entity spawns

commands:
  tealimit:
    description: Basic Command
